name: tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  vulns:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Go list
        run: make go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main